version: "2"
services:
  nginx:
    image: nginx:1.11
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    volumes_from: 
      - php
    links:
      - php
      - mysql
  php:
    build: ./php
    volumes:
      - ../Portfolio:/app
    links:
      - mysql
  mysql:
    build: ./mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment: 
      - 'MYSQL_ROOT_PASSWORD=root'
      - 'MYSQL_DATABASE=portfolio'